AWSTemplateFormatVersion: 2010-09-09

Description: DynamoDB table for storing books' data.

Parameters:
  DynamoDbTableName:
    Type: String
    Description: The name of the DynamoDB table.

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDbTableName
      AttributeDefinitions:
        - AttributeName: "Isbn"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Isbn"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
