AWSTemplateFormatVersion: 2010-09-09

Description: EC2 instane for housing a web API.

Parameters:
  EC2InstanceName:
    Type: String
    Description: The name of the EC2 instance.
  EC2IAMRolesStackName:
    Type: String
    Description: The name of the stack that contains the IAM roles for the EC2 instance.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-09040d770ffe2224f
      InstanceType: t2.nano
      KeyName: grimoire-key-pair
      IamInstanceProfile: !Ref IamInstanceProfile
      UserData:
        # Batch script to install Docker on the EC2 instance.
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo apt-get update -y
          sudo apt-get install -y ca-certificates curl 
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update -y
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceName
      SecurityGroupIds:
        - !Ref SecurityGroupSSH
        - !Ref SecurityGroupServer

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  SecurityGroupServer:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable accessing server via port 80.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Fn::ImportValue: !Sub "${EC2IAMRolesStackName}-EC2InstanceIAMRoleName"
