AWSTemplateFormatVersion: "2010-09-09"

Description: "Elastic Container Repository"

Parameters:
  ECRName:
    Type: String
    Description: The name of the ECR repository.

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRName
      ImageScanningConfiguration:
        scanOnPush: true

Outputs:
  ECRRepositoryName:
    Value: !Ref ECRRepository
    Description: The name of the ECR repository.
    Export:
      Name: !Sub "${AWS::StackName}-ECRRepositoryName"
