AWSTemplateFormatVersion: 2010-09-09

Description: IAM role for accessing a DynamoDB table.

Parameters:
  PolicyName:
    Type: String
    Description: The name of the policy.
  DynamoDbTableStackName:
    Type: String
    Description: The name of the stack that contains the DynamoDB table.

Resources:
  DynamoDbAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Ref PolicyName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - Fn::ImportValue: !Sub "${DynamoDbTableStackName}-DynamoDbTabeArn"

Outputs:
  DynamoDbAccessRoleName:
    Value: !Ref DynamoDbAccessRole
    Description: The name of the IAM role.
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDbAccessRoleName"
