AWSTemplateFormatVersion: 2010-09-09

Description: IAM role for accessing a DynamoDB table.

Parameters:
  EC2InstancePolicyName:
    Type: String
    Description: The name of the policy to attach to the EC2 instance IAM role.
  DynamoDbTableStackName:
    Type: String
    Description: The name of the stack that contains the DynamoDB table.
  SQSQueueStackName:
    Type: String
    Description: The name of the stack that contains the SQS queue.

Resources:
  EC2InstanceIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Ref DynamoDbAccessPolicyName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - Fn::ImportValue: !Sub "${DynamoDbTableStackName}-DynamoDbTabeArn"
              - Effect: Allow
                Action:
                  - sqs:*
                Resource:
                  - Fn::ImportValue: !Sub "${SQSQueueStackName}-SQSQueueArn"

Outputs:
  EC2InstanceIAMRoleName:
    Value: !Ref EC2InstanceIAMRole
    Description: The name of the EC2 instance IAM role.
    Export:
      Name: !Sub "${AWS::StackName}-EC2InstanceIAMRoleName"
