AWSTemplateFormatVersion: "2010-09-09"

Description: "Lambda function to receive messages from SQS with a dead letter queue and an S3 bucket."

Parameters:
  LambdaFunctionName:
    Type: String
    Description: "The name of the Lambda function"
  LambdaImageUri:
    Type: String
    Description: "The URI of the Lambda image"
  SqsQueueName:
    Type: String
    Description: "The name of the SQS queue"
  SqsDeadLetterQueueName:
    Type: String
    Description: "The name of the SQS dead letter queue"
  BucketName:
    Type: String
    Description: The name of the S3 bucket.

Resources:
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaExecutionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
              - Effect: "Allow"
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                  - "sqs:GetQueueUrl"
                Resource: !GetAtt SqsQueue.Arn
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource: !Sub "arn:aws:s3:::${BucketName}/*"

      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Ref LambdaFunctionName
      PackageType: Image
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ImageUri: !Ref LambdaImageUri
      Timeout: 30
      MemorySize: 256

  SqsQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Ref SqsQueueName
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SqsDeadLetterQueue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 120

  SqsDeadLetterQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Ref SqsDeadLetterQueueName
      VisibilityTimeout: 120

  SqsQueueEventSourceMapping:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      BatchSize: 10
      EventSourceArn: !GetAtt SqsQueue.Arn
      FunctionName: !Ref LambdaFunction
      Enabled: true

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  LambdaFunctionArn:
    Description: "The ARN of the Lambda function"
    Value: !GetAtt LambdaFunction.Arn
  SQSQueueArn:
    Description: "The ARN of the SQS queue"
    Value: !GetAtt SqsQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SQSQueueArn"
  SqsDeadLetterQueueArn:
    Description: "The ARN of the SQS dead letter queue"
    Value: !GetAtt SqsDeadLetterQueue.Arn
  S3BucketArn:
    Description: "The ARN of the S3 bucket"
    Value: !GetAtt S3Bucket.Arn
