AWSTemplateFormatVersion: 2010-09-09

Description: EC2 instane for housing a web API along with a DynamoDB table for storing books' data.

Parameters:
  DynamoDbTableName:
    Type: String
    Description: The name of the DynamoDB table.
  EC2InstanceName:
    Type: String
    Description: The name of the EC2 instance.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-09040d770ffe2224f
      InstanceType: t2.nano
      KeyName: grimoire-key-pair
      IamInstanceProfile: !Ref IamInstanceProfile
      UserData:
        # Batch script to install Docker on the EC2 instance.
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo apt-get update -y
          sudo apt-get install -y \
              apt-transport-https \
              ca-certificates \
              curl \
              software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository -y \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
          sudo apt-get update -y
          sudo apt-get install -y docker-ce
      Tags:
        - Key: Name
          Value: !Ref EC2InstanceName
      SecurityGroupIds:
        - !Ref SecurityGroupSSH
        - !Ref SecurityGroupServer
    DependsOn: DynamoDBTable

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  SecurityGroupServer:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable accessing server via port 80.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  IamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref DyanmoDbAccessRole

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDbTableName
      AttributeDefinitions:
        - AttributeName: "Isbn"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Isbn"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DyanmoDbAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !GetAtt DynamoDBTable.Arn
