name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy Web API Template to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: WebApiStack
          template: template-web-api.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            DynamoDbTableName=Book,
            EC2InstanceName=WebApiInstance

      - name: Deploy Web App Template to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: WebAppStack
          template: template-web-app.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            BucketName=grimoire-web-app-bucket
