name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy DynamoDb Table to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: GrimoireDynamoDbTable
          template: dynamodb-table.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            DynamoDbTableName=Book

      - name: Deploy DyamoDb Table Access IAM Role to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: GrimoireDynamoDbAccessRole
          template: iam-role-dynamodb-access.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            PolicyName=grimoire-dynamodb-access-policy,
            DynamoDbTableStackName=GrimoireDynamoDbTable

      - name: Deploy EC2 Instance to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: GrimoireEC2Instance
          template: ec2-instance.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            EC2InstanceName=WebApiInstance,
            DynamoDbAccessRoleStackName=GrimoireDynamoDbAccessRole

      - name: Deploy S3 Static Website Bucket to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: GrimoireStaticWebsite
          template: s3-bucket.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            BucketName=grimoire-static-website-bucket

      - name: Deploy Lambda SQS Event Sourcing Suite to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: GrimoireLambdaSQSEventSourcingSuite
          template: lambda-sqs-bucket.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            LambdaFunctionName=GrimoireLambdaFunction,
            LambdaImageUri=637423253196.dkr.ecr.us-east-2.amazonaws.com/grimoire-lambda:latest,
            SqsQueueName=GrimoireSqsQueue,
            SqsDeadLetterQueueName=GrimoireSqsDeadLetterQueue,
            BucketName=grimoire-event-sourcing-bucket
